server:
  port: 6100
  servlet:
    context-path: /admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin-db
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
