server:
  port: ${random.int(6200,6299)}
  servlet:
    context-path: /records
spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/records-db
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}