server:
  port: ${random.int(6300,6399)}
  servlet:
    context-path: /studies
spring:
  datasource:
    dbcp2:
      url: jdbc:mysql://localhost:3306/studies-db
      username: root
      password: 123456789
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update