spring:
  application:
    name: config-server
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JonathanGGB/Microservicios-clinica.git
          default-label: main
          search-paths: config-data

server:
  port: 6001 